import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import AuthProvider from '@/componets/AuthProvider/AuthProvider';
import TanStackProvider from '@/componets/TanStackProvider/TanStackProvider';

const inter = Inter({
  variable: '--font-Inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  modal,
  children,
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <Toaster position="top-right" />
        <TanStackProvider>
          <AuthProvider>
            {modal}
            {children}
          </AuthProvider>
        </TanStackProvider>
      </body>
    </html>
  );
}
